DROP DATABASE IF EXISTS `fundb`;
CREATE DATABASE IF NOT EXISTS `fundb`;

CREATE USER 'fundb_user'@'%' IDENTIFIED BY 'fundb_password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO 'fundb_user'@'%' WITH GRANT OPTION;

CREATE TABLE IF NOT EXISTS `fundb`.`user`(
	`username` VARCHAR(50),
	`password` VARCHAR(128),
	`createdAt` BIGINT UNSIGNED NOT NULL,
	`updatedAt` BIGINT UNSIGNED,
	`isActive` BOOLEAN DEFAULT true,
	PRIMARY KEY PK_USER(`username`(50))
);
CREATE INDEX user_idx ON `fundb`.`user` (`username`);